
import React from 'react';

const tokens = {
    colors: {
        accent: "#F48847",
        dark: "#134061",
        text: "#1E293B",
        muted: "#64748b",
        lightBg: "#F8FAFC",
        cardBg: "#FFFFFF",
        border: "#E2E8F0",
    }
};

const Header = ({ logoSrc, reportDate, preparedForName }) => (
    <div className="flex justify-between items-center py-4 border-b border-gray-200 mb-8">
        <div>
            {logoSrc ? (
                <img src={logoSrc} alt="Valid Agenda" className="h-6 object-contain" />
            ) : (
                <span className="text-sm font-bold text-[#134061]">VALID AGENDA</span>
            )}
        </div>
        <div className="text-right">
            <div className="text-[10px] font-bold text-[#134061] uppercase tracking-wider">AI Payback Blueprint</div>
            <div className="text-[10px] text-gray-400 mt-1">{reportDate}</div>
        </div>
    </div>
);

const Footer = () => (
    <div className="absolute bottom-6 left-10 right-10 pt-4 border-t border-gray-200 flex justify-between text-[10px] text-gray-400">
        <div>© {new Date().getFullYear()} Valid Agenda. All rights reserved.</div>
        <div>validagenda.com</div>
    </div>
);

const Page = ({ children, className = "", noHeader = false, data }) => (
    <div className={`relative bg-white p-10 mx-auto w-full h-full flex flex-col ${className}`} style={{ breakAfter: 'page', minHeight: '1123px' }}>
        {!noHeader && <Header logoSrc={data.logoSrc} reportDate={new Date(data.reportDate).toLocaleDateString()} preparedForName={data.preparedForName} />}
        <div className="flex-1">
            {children}
        </div>
        <Footer />
    </div>
);

const SectionHeader = ({ chipLabel, title }) => (
    <div className="mb-6">
        <span className="inline-block bg-[#134061] text-white text-[10px] font-bold px-2 py-1 rounded mb-2 tracking-widest uppercase">
            {chipLabel}
        </span>
        <h2 className="text-2xl font-bold text-[#134061]">{title}</h2>
    </div>
);

export const ReportTemplate = ({ data }) => {
    // Determine report date string
    const reportDateStr = new Date(data.reportDate).toLocaleDateString();

    const formatCurrency = (val) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(val);
    const formatNumber = (val) => new Intl.NumberFormat('en-US', { maximumFractionDigits: 0 }).format(val);

    return (
        <div className="report-container font-sans text-slate-800">
            {/* Page 1: Cover */}
            <div className="relative w-full h-full bg-[#134061] text-white p-16 flex flex-col justify-between" style={{ breakAfter: 'page', minHeight: '1123px' }}>
                <div>
                    {data.logoSrc && <img src={data.logoSrc} alt="Logo" className="w-40 mb-12 brightness-0 invert" />}
                    <div className="w-12 h-1 bg-[#F48847] mb-8"></div>
                    <h1 className="text-6xl font-extrabold leading-tight mb-6">
                        The AI Payback<br />Blueprint
                    </h1>
                    <p className="text-2xl text-white/70 font-light max-w-lg">
                        A quantified roadmap to outcome-driven automation for {data.preparedForName}.
                    </p>
                </div>
                <div>
                    <div className="text-xs font-bold text-[#F48847] uppercase tracking-widest mb-2">Confidential Analysis</div>
                    <div className="text-xs text-white/50">Generated by Valid Agenda. Outcome-driven AI.</div>
                </div>
            </div>

            {/* Page 2: Executive Summary */}
            <Page data={data}>
                <SectionHeader chipLabel="THE NUMBERS" title="The Capital Opportunity" />

                <div className="grid grid-cols-4 gap-4 mb-12">
                    <div className="bg-white border rounded-lg p-5 shadow-sm">
                        <div className="text-[10px] font-bold text-gray-400 uppercase tracking-wide mb-2">Cost of Inaction</div>
                        <div className="text-2xl font-extrabold text-[#F48847]">{formatCurrency(data.currentAnnualCost)}</div>
                    </div>
                    <div className="bg-white border rounded-lg p-5 shadow-sm">
                        <div className="text-[10px] font-bold text-gray-400 uppercase tracking-wide mb-2">Reclaimable Capital</div>
                        <div className="text-2xl font-extrabold text-[#F48847]">{formatCurrency(data.potentialSavings)}</div>
                    </div>
                    <div className="bg-white border rounded-lg p-5 shadow-sm">
                        <div className="text-[10px] font-bold text-gray-400 uppercase tracking-wide mb-2">Expert Hours Wasted</div>
                        <div className="text-2xl font-extrabold text-[#134061]">{formatNumber(data.weeklyHoursCaptured * 52)}</div>
                    </div>
                    <div className="bg-white border rounded-lg p-5 shadow-sm">
                        <div className="text-[10px] font-bold text-gray-400 uppercase tracking-wide mb-2">Recovery Potential</div>
                        <div className="text-2xl font-extrabold text-[#134061]">50%</div>
                    </div>
                </div>

                <div className="mt-8 mb-12">
                    <SectionHeader chipLabel="THE STAKES" title="The Cost of Inaction" />
                    <div className="bg-slate-100 border border-slate-200 rounded-xl p-6 flex flex-row items-center gap-6">
                        <div className="flex-1 text-sm text-slate-600 leading-relaxed">
                            Staying manual is an active decision to burn <span className="font-bold text-[#F48847]">{formatCurrency(data.doNothingAnnualCost)}</span> every year.
                            This is not just "busywork"—it’s a drain on your culture and your capital.
                            <br /><br />
                            By automating these workflows, you reclaim <span className="font-bold text-slate-900">{formatNumber(data.doNothingHoursPerYear)}</span> expert hours annually.
                        </div>
                        <div className="w-48 border-l border-slate-300 pl-6 flex flex-col justify-center">
                            <div className="text-3xl font-extrabold text-[#F48847]">{formatCurrency(data.doNothingAnnualCost)}</div>
                            <div className="text-[10px] font-bold text-slate-500 uppercase mt-1">Annual Waste Projection</div>
                        </div>
                    </div>
                </div>

                <div className="bg-slate-100 p-8 rounded-lg mt-8">
                    <h3 className="text-lg font-bold text-[#134061] mb-3">Payback-first AI. No science projects.</h3>
                    <p className="text-sm text-slate-600 leading-relaxed">
                        AI is not a strategy—it is leverage. We believe outcomes beat activity.
                        If it doesn’t reduce cost, save time, or lower risk, it’s not work; it’s entertainment.
                        <br /><br />
                        Our approach is simple: Baseline the workflow, choose the high-payback intervention,
                        install guardrails, and measure the math. Every week.
                    </p>
                </div>
            </Page>

            {/* Page 3: Portfolio View */}
            <Page data={data}>
                <SectionHeader chipLabel="THE PORTFOLIO" title="Strategic Priority Matrix" />

                <div className="border border-slate-200 rounded-xl bg-slate-50 p-6 mb-8 h-[500px] flex flex-col justify-center relative overflow-hidden">
                    {/* CSS Grid Matrix */}
                    <div className="relative w-full h-full border-l border-b border-slate-300">
                        {/* Background Quadrants */}
                        <div className="absolute top-0 right-0 w-1/2 h-1/2 bg-[#F48847]/5"></div> {/* Top Right */}
                        <div className="absolute top-0 left-0 w-1/2 h-1/2 bg-slate-500/5"></div> {/* Top Left */}
                        <div className="absolute bottom-0 right-0 w-1/2 h-1/2 bg-[#134061]/5"></div> {/* Bottom Right */}
                        <div className="absolute bottom-0 left-0 w-1/2 h-1/2 bg-slate-200/10"></div> {/* Bottom Left */}

                        {/* Grid Lines */}
                        <div className="absolute top-1/2 left-0 right-0 h-px bg-slate-300 border-t border-dashed border-slate-300"></div>
                        <div className="absolute left-1/2 top-0 bottom-0 w-px bg-slate-300 border-l border-dashed border-slate-300"></div>

                        {/* Labels */}
                        <div className="absolute -left-8 top-1/2 -translate-y-1/2 -rotate-90 text-[10px] text-slate-400 font-bold tracking-wider">VIABILITY (READINESS)</div>
                        <div className="absolute bottom-[-24px] left-1/2 -translate-x-1/2 text-[10px] text-slate-400 font-bold tracking-wider">IMPACT (COST SAVINGS)</div>

                        {/* Plot Points */}
                        {(() => {
                            const validTasks = (data.tasks || []).filter(t => t.metrics && t.metrics.annualCost);
                            const maxImpact = Math.max(...validTasks.map(t => t.metrics.annualCost), 1000);

                            return validTasks.map((task, i) => {
                                const impactScore = (task.metrics.annualCost / maxImpact) * 100; // 0-100 (X)

                                // Recalculate Viability (Match logic in DecisionMatrix.js)
                                const readiness = task.readinessScore || 0;
                                const pain = (task.pain || 5) / 10;
                                const viability = (readiness * 0.6 + pain * 0.4) * 100; // 0-100 (Y)

                                // Color Logic
                                let color = "#94a3b8";
                                if (impactScore >= 50 && viability >= 50) color = "#F48847"; // Quick Win
                                else if (impactScore < 50 && viability >= 50) color = "#64748B"; // Low Hanging
                                else if (impactScore >= 50 && viability < 50) color = "#134061"; // Major

                                // Clamp values to keep within box (padding handling)
                                const x = Math.max(2, Math.min(98, impactScore));
                                const y = Math.max(2, Math.min(98, viability));

                                return (
                                    <div
                                        key={i}
                                        className="absolute w-4 h-4 rounded-full border-2 border-white shadow-sm z-10"
                                        style={{
                                            backgroundColor: color,
                                            left: `${x}%`,
                                            bottom: `${y}%`,
                                            transform: 'translate(-50%, 50%)'
                                        }}
                                    ></div>
                                );
                            });
                        })()}
                    </div>
                </div>
                <div className="text-center text-xs text-slate-400 mb-8 mt-6">
                    Impact vs. Viability. We focus on the high-payback, high-readiness workflows in the top right.
                </div>

                <div className="bg-white border-l-4 border-[#F48847] p-6 shadow-sm">
                    <p className="text-sm text-slate-700 leading-relaxed">
                        <span className="font-extrabold">Outcomes beat activity.</span> Most teams start with the "smartest" ideas. We start with the ones that pay back.
                        Our matrix categorizes tasks by their immediate recovery potential and technical readiness.
                    </p>
                </div>
            </Page>

            {/* Page 4: Roadmap */}
            <Page data={data}>
                <SectionHeader chipLabel="THE ROADMAP" title="Top Payback Opportunities" />

                <div className="grid grid-cols-2 gap-6 mb-12">
                    {(data.opportunities || []).slice(0, 2).map((op, idx) => (
                        <div key={idx} className="bg-white border border-slate-200 rounded-xl p-6 shadow-sm">
                            <div className="flex justify-between items-start mb-4">
                                <span className="bg-[#F48847] text-white text-[10px] font-bold px-2 py-1 rounded uppercase">{op.tag || "Priority"}</span>
                                <span className="text-sm font-extrabold text-[#134061]">{formatCurrency(op.savings)} Recovery</span>
                            </div>
                            <h3 className="text-lg font-bold text-[#134061] mb-2 leading-tight min-h-[56px]">{op.title}</h3>
                            <p className="text-xs text-slate-500 leading-relaxed">
                                {op.reason || "Repeatable work with predictable savings potential."}
                            </p>
                        </div>
                    ))}
                </div>

                <div className="mt-auto mb-20">
                    <SectionHeader chipLabel="NEXT STEPS" title="Move from estimates to outcomes" />
                    <div className="bg-[#134061] rounded-xl p-8 text-white relative overflow-hidden">
                        <div className="relative z-10 flex flex-row gap-8">
                            <div className="flex-1">
                                <h3 className="text-2xl font-bold mb-2">The AI Payback Sprint</h3>
                                <p className="text-sm text-slate-300 mb-6 leading-relaxed">
                                    The math above shows the opportunity. The Sprint makes it real.
                                    In 30 days, we baseline one critical workflow, install the guardrails,
                                    and prove the payback. No "transformation" fluff. Just outcomes.
                                </p>
                                <ul className="space-y-2 mb-6">
                                    {['Confirm the baseline (Time, Cost, Accuracy)', 'Install Guardrails (Ownership & Safety)', 'Deploy 30/60/90 Day Implementation Path'].map((item, i) => (
                                        <li key={i} className="flex items-center text-sm font-medium">
                                            <span className="w-1.5 h-1.5 bg-[#F48847] rounded-full mr-3"></span>
                                            {item}
                                        </li>
                                    ))}
                                </ul>
                                <div className="text-sm font-bold text-[#F48847]">Book your sprint evaluation: validagenda.com/book</div>
                                <div className="text-[10px] text-slate-500 mt-2">This is an estimate. The Sprint confirms the baseline and payback.</div>
                            </div>
                            {data.bookingQrDataUri && (
                                <div className="w-32 flex-shrink-0 flex flex-col justify-center items-center bg-white/5 rounded-lg p-2">
                                    <img src={data.bookingQrDataUri} alt="QR Code" className="w-full h-auto rounded" />
                                </div>
                            )}
                        </div>
                    </div>
                </div>
            </Page>
        </div>
    );
};
