import React from "react";
import { View, Text, Image } from "@react-pdf/renderer";
import { styles, tokens } from "../styles";

export function Cover({ preparedForName, logoSrc }) {
    return (
        <View style={styles.coverPage}>
            <View>
                {logoSrc && <Image src={logoSrc} style={{ width: 140, marginBottom: 40 }} />}
                <View style={{ height: 2, width: 40, backgroundColor: tokens.colors.accent, marginBottom: 20 }} />
                <Text style={{ fontSize: 40, fontWeight: '800', lineHeight: 1.1, marginBottom: 12 }}>
                    The AI Payback{"\n"}Blueprint
                </Text>
                <Text style={{ fontSize: 18, color: 'rgba(255,255,255,0.7)', fontWeight: '400' }}>
                    A quantified roadmap to outcome-driven{"\n"}automation for {preparedForName}.
                </Text>
            </View>

            <View>
                <Text style={{ fontSize: 10, color: tokens.colors.accent, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 1.5, marginBottom: 4 }}>
                    Confidential Analysis
                </Text>
                <Text style={{ fontSize: 10, color: 'rgba(255,255,255,0.5)' }}>
                    Generated by Valid Agenda. Outcome-driven AI.
                </Text>
            </View>
        </View>
    );
}
